site_name: Capacitor y su solución númerica

theme: 
  name: "material"

nav:
  - index.md
  - tutorials.md
  - reference.md
  - explanation.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - admonition
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
